apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  annotations:
    objectset.rio.cattle.io/applied: '{"kind":"Service","apiVersion":"rio.cattle.io/v1","metadata":{"name":"add-svr","namespace":"default","creationTimestamp":null,"labels":{"objectset.rio.cattle.io/hash":"9668f89789f14d885cc9df657a29324a76b40809"},"annotations":{"objectset.rio.cattle.io/id":"stack-riofile","objectset.rio.cattle.io/owner-gvk":"rio.cattle.io/v1,
      Kind=Stack","objectset.rio.cattle.io/owner-name":"riodemo","objectset.rio.cattle.io/owner-namespace":"default"}},"spec":{"scale":1,"image":"miletwo/add-svr:v1","ports":[{"protocol":"HTTP","port":8080,"targetPort":8080}]},"status":{}}'
    objectset.rio.cattle.io/id: stack-riofile
    objectset.rio.cattle.io/owner-gvk: rio.cattle.io/v1, Kind=Stack
    objectset.rio.cattle.io/owner-name: riodemo
    objectset.rio.cattle.io/owner-namespace: default
  creationTimestamp: "2019-08-05T15:59:37Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2019-08-05T16:06:16Z"
  finalizers:
  - wrangler.cattle.io/stack-service-object-controller-remove
  - wrangler.cattle.io/autoscale-service-object-controller-remove
  - wrangler.cattle.io/stack-service-build-object-controller-remove
  - wrangler.cattle.io/routing-service-object-controller-remove
  generation: 25
  labels:
    objectset.rio.cattle.io/hash: 9668f89789f14d885cc9df657a29324a76b40809
  name: add-svr
  namespace: default
  resourceVersion: "86145"
  selfLink: /apis/rio.cattle.io/v1/namespaces/default/services/add-svr
  uid: 067c1b1f-b79a-11e9-856b-025000000001
spec:
  image: miletwo/add-svr:v1
  ports:
  - port: 8080
    protocol: HTTP
    targetPort: 8080
  scale: 1
status:
  conditions:
  - lastUpdateTime: "2019-08-05T16:04:22Z"
    status: "True"
    type: DeployedStackService
  - lastUpdateTime: "2019-08-05T16:04:22Z"
    status: "True"
    type: DeployedAutoscaleService
  - lastUpdateTime: "2019-08-05T16:04:22Z"
    status: "True"
    type: DeployedStackServiceBuild
  - lastUpdateTime: "2019-08-05T16:04:22Z"
    status: "True"
    type: DeployedRoutingService
  deploymentStatus:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2019-08-05T15:59:37Z"
      lastUpdateTime: "2019-08-05T15:59:42Z"
      message: ReplicaSet "add-svr-66647bd59f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-08-05T16:04:22Z"
      lastUpdateTime: "2019-08-05T16:04:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
  endpoints:
  - https://add-svr-v0-default.6pk65w.on-rio.io:9443
  scaleStatus:
    ready: 2
    updated: 2
